### ISSUE TITLE
CppUnit dependency is not needed.

### ISSUE THREAD

**Issue by romeojulietthotel** [mhostetter/gr-adsb#10]
The CppUnit dependency is not really needed. Gnuradio does not make that a hard requirement. And CppUnit is only needed/used when running  `make test .`

**Comment by mhostetter** [comment]
I'm going to leave the dependency since it's suggested by GNU Radio. Plus, if I get really fancy, I will probably add QA tests later on.

**Comment by romeojulietthotel** [comment]
Suggested by Gnuradio but I recall that building Gnuradio itself doesn't even require it. So looks like a "do as I say not as I do" recommendation. And/or poorly maintained OOT templates.
