### ISSUE TITLE
Problem with decoding ADS-B messages with 16 bit SDR

### ISSUE THREAD

**Issue by akaranovski** [mhostetter/gr-adsb#40]
Hello thanks for the module.

I just wonder whether it can cause problem while decoding messages if SDR is 16 bit and not 8 or 12?
If so in which part of Framer or Demodulator this can be tuned?

Thanks

**Comment by akaranovski** [comment]
Below are both screens from the same place, same rf chain different SDRs
![Screenshot from 16 -bit ADC SDR](https://user-images.githubusercontent.com/79315255/117842419-f6c2e500-b28e-11eb-9402-c9f163671f08.png)
![Screenshot from 12-bit ADC SDR](https://user-images.githubusercontent.com/79315255/117842440-fd515c80-b28e-11eb-9bb3-f778fd722ca1.png)

**Comment by akaranovski** [comment]
Please  below is GUI with threshold 0.00001
![Screenshot 16 bit](https://user-images.githubusercontent.com/79315255/117851029-f4fd1f80-b296-11eb-9dbd-595d0f71ed0b.png)

**Comment by akaranovski** [comment]
Sure

**Comment by akaranovski** [comment]
![Flowgraph](https://user-images.githubusercontent.com/79315255/117856885-37295f80-b29d-11eb-8b5e-b1e60b0ca774.png)

**Comment by mhostetter** [comment]
Something along the lines of this...

Maybe one for the "good" case and the "bad" case.

![image](https://user-images.githubusercontent.com/12112573/117858598-0a088d00-b25c-11eb-98d0-dc4ef427ee0a.jpeg)

**Comment by akaranovski** [comment]
Hi Matt,

I tried to catch SOB and EOB not sure how successful it was but seems issue with EOB missing.
First I changed Y axis from 1 to 0.0005 and some staff starts to appear.
Screen is below this is non working case 16-bit ADC.
![Screenshot with SOBs](https://user-images.githubusercontent.com/79315255/117940646-56b29d80-b31a-11eb-8fcf-05e624f6b314.png)

**Comment by mhostetter** [comment]
I think the SOP/EOB burst tags may have been from a previous debug version. From looking at the signal, I wouldn't expect the CRC to pass. What does your front end look like? Antenna is pretty important here. And are there any differences between the 12-bit setup that works?

**Comment by akaranovski** [comment]
I got your point, but seems the problem caused by another reason.
Will try to explain:  seems MSPS on 16-bit ADC getting lower sample rate via decimation of max available.
For example max msps is 160 and in order to get 2 it is decimating signal which brings the loss of signal strength.
Do you have idea how to avoid signal loss due to decimation?

**Comment by mhostetter** [comment]
What kind of SDR are you using? Is the ADC running at 160 Msps and then in FPGA downsampling to 4 Msps? If so, the digital filters in there should be good. Do you have a hardware filter out front? If not, out-of-band signal may be saturating your receiver's front-end and stealing your dynamic range.

**Comment by akaranovski** [comment]
This is USRP SDR custom version and it has 325 Msps.
But the question I have do I lose signal when it decimates the signal until 2msps or FPGA filters should save info?
Cause when I put 160Msps signal strenght rising immideately by 30 dBm.
Now I am lost why simple 12 bit Pluto can catch the ADSB and well designed USRP with higher MSPS can not ?
Seems it goes out of synchro with SOB.
What you think?

**Comment by akaranovski** [comment]
About antenna I use same antenna as for 12 bit SDR it is self made and checked in terms of VSWR and the exact frequency.
It works with pluto easily.

**Comment by mhostetter** [comment]
You should be able to tell your USRP to limit the RF bandwidth even before digitizing. Try setting this parameter in the USRP source block. The notable setting the "Ch0: Bandwidth (Hz)". The default in my flowgraph is 0, which is wide open.

![image](https://user-images.githubusercontent.com/12112573/118044698-fd139880-b344-11eb-9cbe-35f19adacff1.png)

**Comment by mhostetter** [comment]
@akaranovski did you have success?

**Comment by akaranovski** [comment]
Hi Matt,
I will close the topic as it was solved after firmware upgrade of device.

Thanks
